// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQafcw8dCCqNK7ERwat7vH0v4cOlodeI',
    appId: '1:736611704844:web:397876233d1d8b7a4a0e29',
    messagingSenderId: '736611704844',
    projectId: 'nadirbrothersorderapp',
    authDomain: 'nadirbrothersorderapp.firebaseapp.com',
    storageBucket: 'nadirbrothersorderapp.appspot.com',
    measurementId: 'G-MYFJQH2SEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzyQQnPP4pnlCZaukTcR6o6v8G_rl6Tbg',
    appId: '1:736611704844:android:d0dbe13547636c8b4a0e29',
    messagingSenderId: '736611704844',
    projectId: 'nadirbrothersorderapp',
    storageBucket: 'nadirbrothersorderapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrRtb5QRzfcUSoMK_p3FeZyw30chhI1nI',
    appId: '1:736611704844:ios:91ceb8ed295aa4704a0e29',
    messagingSenderId: '736611704844',
    projectId: 'nadirbrothersorderapp',
    storageBucket: 'nadirbrothersorderapp.appspot.com',
    iosClientId: '736611704844-u8l4pbroefrijddvbl5sev38fv5ljim5.apps.googleusercontent.com',
    iosBundleId: 'com.mahrukhdev.nadirBrothersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrRtb5QRzfcUSoMK_p3FeZyw30chhI1nI',
    appId: '1:736611704844:ios:e8622c87436b9ec24a0e29',
    messagingSenderId: '736611704844',
    projectId: 'nadirbrothersorderapp',
    storageBucket: 'nadirbrothersorderapp.appspot.com',
    iosClientId: '736611704844-mb29ooo3ap3qs5l2h82tqqbiohefm5u6.apps.googleusercontent.com',
    iosBundleId: 'com.mahrukhdev.nadirBrothersApp.RunnerTests',
  );
}
